### ISSUE TITLE
Demonstrate asyncness

### ISSUE THREAD

**Issue by Kukkimonsuta** [nareshbhatia/mobx-shop#2]
Currently transitions are resolved instantly, however in real world loading data takes time. I'd like to see in this sample what are the options on async data loading - especially if it's possible to use "github style" navigation (click link -> data loading with progress bar on top -> change UI once loaded).

**Comment by nareshbhatia** [comment]
Excellent suggestion! I have revamped the ItemStore to introduce a `isLoading` flag there. The `onEnter` hooks now simply kickoff data loading, setting the `isLoading` flag to true. This triggers the display of a busy cursor, until the real data has been returned and the `isLoading` flag has been turned off. The `ItemStore` has been modified to simulate a 200ms delay. You can increase it to whatever you like to see a pronounced effect of async loading.
